<?php return array (
  'Summary' => 'Zusammenfassung',
  'Category' => 'Kategorie',
  'Milestone' => 'Meilenstein',
  'Tags' => 'Tags',
  'Notify People' => 'Benachrichtigung an Personen',
  'Add discussion' => 'Neuer Beitrag',
  'New Discussion' => 'Neuer Beitrag',
  'Update Discussion' => 'Beitrag ändern',
  'Discussions' => 'Beiträge',
  'There are no discussions on this page' => 'Keine Beiträge auf dieser Seite',
  'Discussion' => 'Beitrag',
  'by <a href=":user_url">:user_name</a>' => 'von <a href=":user_url">:user_name</a>',
  'No discussions in this category' => 'Keine Beiträge in dieser Kategorie',
  'Start one now' => '',
  'No discussions here' => 'Keine Beiträge hier',
  'All Discussions' => 'Alle Beiträge',
  'Manage Categories' => 'Kategorien verwalten',
  'List' => 'Liste',
  'Add Discussion' => 'Beitrag hinzufügen',
  'Discussion <a href=":url">:name</a> has been created' => 'Beitrag <a href=":url">:name</a> erstellt',
  'Page :page' => 'Seite :page',
  'There are no comments on this page!' => 'Keine Kommentare auf dieser Seite!',
  'About Discussions' => 'Über Beiträge',
  'Just Like Online Forums' => '',
  'Discussions let you create a number of topics and discuss them with your team and clients. It works just like online forums - system will tell you when there are new messages in a topic and discussions with most recent comments are listed on top' => 'Beiträge erlauben das Erstellen von Themen und die Diskussionen im Team und mit Kunden. Beiträge funktionieren wie Online-Foren - das System wird Ihnen mitteilen, wenn es neue Nachrichten gibt. Neueste Kommentare werden zuerst angezeigt.',
  'Organize in Categories and Associate with Milestones' => '',
  'Discussions can be sorted in categories and associated with milestones; both relations are optional. Filter discussions by category using the tabs on the right' => '',
  'Attach Unlimited Number of Files' => '',
  'Every discussion message can have an unlimited number of attachments. System will use icons for various file types and thumbnails for images' => 'Jeder Beitrag kann eine unbegrenzte Anzahl von Anhängen haben. Das System benutzt Symbole für unterschiedliche Dateitypen und erstellt automatisch eine Vorschau von Bildern.',
  'Email Notifications' => '',
  'Subscribe to a discussion to receive an email notification when new message is posted. Discussion subscribers can be managed using Manage Subscriptions tool (available from Options menu)' => '',
  'Discussion :discussion_name has been started' => 'Beitrag :discussion_name wurde erstellt',
  'Discussion :name has been updated' => 'Beitrag :name wurde aktualisiert',
  'Discussion summary is required' => 'Zusammenfassung fehlt',
  'Discussion message is required' => 'Inhalt fehlt',
  'Minimal content value is 5 characters' => '',
  'Discussion title is required' => 'Titel fehlt',
  'Comment is required' => 'Kommentar fehlt',
  'Discussion categories' => 'Kategorien',
  'Exporting discussions data...' => 'Beitragsdaten exportieren...',
  'Discussion summary is required. Min length is 3 letters' => 'Zusammenfassung fehlt. Mindestlänge 3 Zeichen',
) ?>