<?php return array (
  'Summary' => 'Zusammenfassung',
  'Full description' => 'Komplette Beschreibung',
  'Visibility' => 'Sichtbarkeit',
  'Milestone' => 'Meilenstein',
  'Tags' => 'Tags',
  'New Checklist' => 'Neue Checkliste',
  'Completed Checklists' => 'Abgeschlossene Checklisten',
  ':open open tasks of :total tasks in the list' => ':open offene Aufgaben in :total Aufgaben in Liste',
  'There are no active checklists here' => 'Keiner aktiven Checklisten',
  'Would you like to <a href=":add_url">create one</a>' => 'Möchten Sie eine neue <a href=":add_url">Checkliste hinzufügen</a>?',
  'Edit checklist' => 'Checkliste bearbeiten',
  'Checklists' => 'Checklisten',
  'Active Checklist' => 'Aktive Checkliste',
  'There are no active checklists in this project' => 'Keine aktiven Checklisten in diesem Projekt',
  'Completed Checklist' => 'Abgeschlossene Checklisten',
  'Checklist' => 'Checkliste',
  'Active Checklists' => 'Aktive Checklisten',
  'Tasks' => 'Aufgaben',
  'Add Checklist' => 'Checkliste hinzufügen',
  'Checklists <a href=":url">:name</a> has been created' => 'Checkliste <a href=":url">:name</a> erstellt',
  'Open' => 'Offen',
  'Description for this checklist is not provided' => 'Keine Beschreibung für diese Checkliste',
  'About Checklists' => 'Über Checklisten',
  'Checklist is a list of tasks that need to be completed for list to be completed. When all tasks in a checklists are completed list is also completed automatically. Every task in a list can have priority, due date and multiple assignees' => 'Checklisten sind Aufgabenlisten, die abgearbeitet werden müssen, damit die Liste abgeschlossen ist. Sobald alle Aufgaben in einer Liste abgeschlossen wurden, ist die Liste automatisch ebenfalls abgeschlossen. Jede Aufgabe in einer Liste kann eine Priorität, Fälligkeitsdatum und mehrere Verantwortliche haben.',
  'Subscribe to checklist tasks to receive email notification tasks are completed or reopened' => 'Verfolgen Sie Checklisten, um E-Mail-Benachrichtigungen über neue Aufgaben, deren Fertigstellung oder Wiedereröffnung zu erhalten.',
  'Checklist :name has been added' => 'Checkliste :name erstellt',
  'Checklist :name has been updated' => 'Checkliste :name geändert',
  'Exporting checklists data...' => 'Daten werden exportiert...',
  'Checklist summary is required' => 'Zusammenfassung fehlt',
) ?>