<?php return array (
  'Content' => 'Inhalt',
  'Create a New Version' => 'Neue Version erstellen',
  'File Under' => 'Ablegen unter',
  'Milestone' => 'Meilenstein',
  'Tags' => 'Tags',
  'Notify People' => 'Personen benachrichtigen',
  'Older Versions' => 'Ältere Versionen',
  'Subpages' => 'Unterseiten',
  'Page / Author' => 'Seite / Autor',
  'Revision' => 'Version',
  'Comments' => 'Kommentare',
  'Create a New Page' => 'Neue Seite erstellen',
  'New page' => 'Neue Seite',
  'Edit page' => 'Seite bearbeiten',
  'You are looking at <strong>revision #:num</strong> of ":name" page.<br /><br />You can also check out <a href=":url">the latest version of this page</a>.' => 'Sie sehen <strong>Version #:num</strong> von Seite ":name".<br /><br /> Sie können auch die <a href=":url">aktuelle Version dieser Seite anzeigen</a>.',
  'Revisions' => 'Versionen',
  'Add Page' => 'Neue Seite',
  'Page <a href=":url">:name</a> has been created' => 'Seite <a href=":url">:name</a> erstellt',
  'Parent' => 'Hauptseite',
  'Page ":name" has been created' => 'Seite ":name" erstellt',
  'Page ":name" has been updated' => 'Seite ":name" geändert',
  'Pages' => 'Seiten',
  'New Page' => 'Neue Seite',
  'Exporting pages data...' => 'Daten werden exportiert...',
  'New version' => 'Neue Version',
  'Page Revision' => 'Seitenversion',
  'Welcome to pages section of <b>:project_name</b> project.' => 'Willkommen im Seiten-Bereich von Projekt <b>:project_name</b>',
) ?>