<?php return array (
  'About Milestones' => 'Über Meilensteine',
  'Milestones Mark Key Points in a Project' => 'Meilensteine markieren Schlüsselstellen in einem Projekt',
  'Milestones mark key points in a project so you can have a bird-eye view over things that needs to be done, when and who is responsible. Milestone can be a single day event or a time period with start and due date. When you need more details, you can click on a milestone\'s name to "zoom in" and see all related discussions, files and tasks' => '',
  'Keep Your Calendar Application in Sync with Milestones' => '',
  'If you want to have milestones synchronized with calendars in your favorite calendar application (iCal, Outlook 2007, Google Calendar), then subscribe to iCalendar feed provided by the system. On the Calendar page you can find global feed with milestones and tasks from all active projects. The system also provides a feed for each project and you can find it by visiting overview page of the particular project' => '',
  'Email Notifications' => 'E-Mail Benachrichtigunen',
  'Subscribe to a milestone to receive email notification when it is completed or reopened. The person responsible for the milestone can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => '',
  'Summary' => 'Zusammenfassung',
  'Start on' => 'Anfangsdatum',
  'Due on' => 'Enddatum',
  'Notes' => 'Hinweise',
  'Priority' => 'Priorität',
  'Tags' => 'Tags',
  'Assignees' => 'Beteiligte',
  'Notify Assignees' => 'Benachrichtigen',
  'New Milestone' => 'Neuer Meilenstein',
  'Completed Milestones' => 'Abgeschlossene Meilensteine',
  'There is not completed milestones in this project. <a href=":add_url">Create a milestone</a>.' => 'Keine abgeschlossenen Meilensteine in diesem Projekt. <a href=":add_url">Meilenstein hinzufügen</a>.',
  'Edit Milestone' => 'Meilenstein bearbeiten',
  '<a href=":url">Click here</a> if you wish to reschedule this milestone.' => '<a href=":url">Hier klicken</a> um Meilenstein neu zu planen.',
  'Milestones' => 'Meilensteine',
  'Milestone' => 'Meilenstein',
  'Active milestones' => 'Aktive Meilensteine',
  'iCalendar' => 'iCalendar',
  'No active milestones here' => 'Keine aktiven Meilensteine',
  'Would you like to <a href=":add_url">create one</a>' => 'Möchten Sie einen neuen <a href=":add_url">Meilenstein hinzufügen</a>?',
  'Add Milestone' => 'Meilenstein hinzufügen',
  'Milestone <a href=":url">:name</a> has been created' => 'Meilenstein <a href=":url">:name</a> hinzugefügt',
  'Reschedule milestone' => 'Meilenstein neu planen',
  'With successive milestones' => 'Mit nachfolgenden Meilensteinen',
  'Reschedule' => 'Neu planen',
  'Due On' => 'Fällig am',
  'From / To' => 'Von / An',
  'Add to Milestone' => 'Add',
  'No notes...' => 'Keine Hinweise...',
  'No tasks in this milestone...' => 'Keine Aufgaben in Meilenstein...',
  'Milestone ":name" has been created' => 'Meilenstein ":name" wurde hinzugefügt',
  'Milestone ":name" has been updated' => 'Meilenstein ":name" wurde aktualisiert',
  'or' => 'oder',
  'Exporting milestones data...' => 'Meilenstein-Daten werden exportiert...',
  'Unknown Milestone' => 'Unbekannter Meilenstein',
  'This milestone does not have any successive milestones' => 'Meilenstein hat keine nachfolgenden Meilensteine',
  'Adjust all successive milestone by the same number of days' => 'Nachfolgende Meilensteine um die selbe Anzahl Tage verschieben',
  'Adjust only selected successive milestones by the same number of days' => 'Nur ausgewählte Meilensteine um die selbe Anzahl Tage verschieben',
  'Don\'t change anything' => 'Keine Änderung',
  'Milestone name is required' => 'Name fehlt',
  'Start date is required' => 'Anfangsdatum fehlt',
  'Due date is required' => 'Enddatum fehlt',
  'Start date needs to be before due date' => 'Anfangsdatum muss vor Enddatum sein ',
) ?>