<?php return array (
  'Submit Ticket / :company' => 'Ticket erstellen / :company',
  'Submit Ticket' => 'Ticket erstellen',
  'Your Email Address' => 'Ihre E-Mail-Adresse',
  'Your Name' => 'Ihr Name',
  'Category' => 'Kategorie',
  'Priority' => 'Priorität',
  'Summary' => 'Zusammenfassung',
  'Full Description' => 'Ausführliche Beschreibung',
  'Type the code shown' => 'Geben Sie folgende Zeichenfolge ein',
  'Public Submit Settings' => 'Einstellung öffentliche Ticket-Erstellung',
  'Project for tickets:' => 'Projekt für Tickets:',
  'Enable captcha:' => 'Captcha aktivieren:',
  'Enable public submit:' => 'Öffentliche Ticket-Erstellung aktivieren',
  'When enabled, Public Submit module will let people submit tickets through a form on your website without having to be a registered and logged in activeCollab. This module is great for receiving support requests or getting feedback from users' => 'Die öffentliche Ticket-Erstellung ermöglicht die Erstellung neuer Tickets über ein Formular auf Ihrer Webseite ohne eine Registrierung und Anmeldung in activeCollab. Dies ist besonder für Support-Anfragen oder Feedback von Benutzern praktisch.',
  'Public Submit is <strong>enabled</strong>' => 'Öffentliche Ticket-Erstellung ist <strong>aktiviert</strong>',
  'Submission form is located here: <a href=":url" target="_blank">:url</a>' => 'Erstellungsformular befindet sich hier: <a href=":url" target="_blank">:url</a>',
  'After user submits data, a new ticket is created in <a href=":url">:project_name</a> project.' => 'Nachdem ein Benutzer ein Ticket erstellt hat befindet sich dieses in Projekt <a href=":url">:project_name</a>.',
  'You need to specify default project for newly created tickets first.' => 'Sie müssen ein Standardprojekt für neu erstellte Tickets angeben.',
  'GD Library is required for captcha protection. <a href=":gd_url">Read more about GD Library</a>' => 'GDLib (PHP) wird für Captcha-Funktion benötigt. <a href=":gd_url">Weitere Informationen</a>.',
  'Public Submit is <strong>disabled</strong>' => 'Öffentliche Ticket-Erstellung ist <strong>deaktiviert</strong>',
  'Public Submit' => 'Öffentliche Tickets',
  'Public Submit settings have been updated' => 'Einstellungen gespeichert',
  'Code you entered is not valid' => 'Die eingegeben Zeichenfolge ist nicht korrekt',
  'Information about Public Submit module' => 'Informationen über Modul',
) ?>