<?php return array (
  'About Files' => 'Über Dateimodul',
  'Upload Files, File Revisions and Collaborate' => '',
  'Use Files section to upload files, discuss them, upload and compare versions and more. You can upload and track versions of any file. Files attached to objects in other sections of project are also listed here' => '',
  'Organize in Categories and Associate with Milestones' => '',
  'Files can be sorted in categories and associated with milestones; both relations are optional. Filter files by category using the tabs on the right' => '',
  'Have a Discussion with your Team or Clients' => '',
  'Post an unlimited number of comments. Use them to discuss file and file revisions with your colleagues and clients' => 'Unbegrenzte Anzahl Kommentare hinzufügen. Diskutieren Sie über Dateien und Versionen mit Kollegen und Kunden.',
  'Email Notifications' => '',
  'Subscribe to a file to receive email notification when new revision is uploaded or new comment is posted. The Person who uploaded the file can edit the list of subscribers using Manage Subscriptions tool (available from Options menu)' => '',
  'Older Versions' => 'Ältere Versionen',
  'Size and Kind' => 'Größe und Typ',
  'Edit File Details' => 'Datei-Details bearbeiten',
  'Description' => 'Beschreibung',
  'Category' => 'Kategorie',
  'Milestone' => 'Meilenstein',
  'Tags' => 'Tags',
  'Files' => 'Dateien',
  'There are no files on this page' => 'Keine Dateien auf dieser Seite',
  'File' => 'Datei',
  'Latest Version' => 'Aktuelle Version',
  'Download' => 'Download',
  'Page :page' => 'Seite :page',
  'First Version' => 'Erste Version',
  'Upload a New Version' => '',
  'Attached To' => 'Hinzugefügt zu',
  'There are no files in this category' => 'Keine Dateien in dieser Kategorie',
  'Upload now' => '',
  'There are no files to show' => 'Keine Dateien',
  'Files and Attachments' => 'Dateien und Anhänge',
  'Manage Categories' => 'Kategorien verwalten',
  'New Version' => 'Neue Version',
  'Select File' => 'Datei wählen',
  'You are about to upload new version of <a href=":url">":name"</a> file. Older versions of this file will not be deleted but saved for future reference' => 'Sie laden eine neue Version von Datei <a href=":url">":name"</a> hoch. Ältere Versionen werden für zukünftigen Zugriff archiviert.',
  'Add File' => 'Datei hinzufügen',
  'File <a href=":url">:name</a> has been created' => 'Datei <a href=":url">:name</a> erstellt',
  'Upload Files' => 'Dateien hochladen',
  'Notify People' => 'Personen benachrichtigen',
  'Description <i>(optional)</i>' => 'Beschreibung <i>(optional)</i>',
  'Add Another File' => 'Weitere Datei hinzufügen',
  'Upload' => 'Hochladen',
  'File Name' => 'Dateiname',
  'Image preview. <a href=":url">Click to download</a> full size image' => 'Vorschau. <a href=":url">Datei in Originalgröße herunterladen</a>',
  'Description for this file is not provided' => 'Keine Beschreibung für diese Datei',
  'Invalid file - last revision was not found' => 'Ungültige Datei - letzte Version nicht gefunden',
  'File ":name" has been updated' => 'Datei ":name" geändert',
  'File is not uploaded' => 'Datei nicht hochgeladen',
  'File not uploaded' => 'Datei nicht hochgeladen',
  'File categories' => 'Datei-Kategorien',
  'Exporting files data...' => 'Daten werden exportiert...',
  'File name is required' => 'Dateiname fehlt',
  'All files from this page moved to trash' => 'Alle Dateien in Papierkorb verschoben',
  'All revision moved to Trash' => 'Alle Versionen in Papierkorb verschoben',
  'Uploading files' => 'Dateien werden hochgeladen',
  'Done, :files_uploaded files uploaded and :files_failed uploads failed<br />' => 'Fertig, :files_uploaded Dateien hochgeladen und :files_failed fehlgeschlagen<br />',
  'Done, :files_uploaded files uploaded<br />' => 'Fertig, :files_uploaded erfolgreich hochgeladen<br />',
  'Done, :files_failed uploads failed<br />' => 'Fertig, Hochladen von :files_uploaded fehlgeschlagen <br />',
) ?>