<?php return array (
  'Backup Settings' => 'Einstellungen Backup',
  'How many backups to keep:' => 'Anzahl Backups:',
  'Enable backup:' => 'Backup aktivieren:',
  'Automatic backup is <strong>enabled</strong>.' => 'Automatisches Backup ist <strong>aktiviert</strong>.',
  'Your next backup will be approximately <strong>:size</strong> in size.' => 'Nächstes Backupgröße etwa <strong>:size</strong>.',
  'Automatic backup is <strong>disabled</strong>.' => 'Automatisches Backup ist <strong>deaktiviert</strong>.',
  ':number_of_backups last backups will be kept' => ':number_of_backups Backupversionen werden gespeichert',
  'All backups will be kept' => 'Alle Backups werden gespeichert',
  'Existing backups:' => 'Existierende Backups:',
  'Backup folder size: <strong>:size</strong>' => 'Größe Backupordner: <strong>:size</strong>',
  'Backup' => 'Backup',
  'Backup settings have been updated' => 'Einstellung Backup gespeichert',
  'Automatic backup of your activeCollab installation' => 'Automatisches Backup Ihrer activeCollab-Installation',
) ?>