<?php return array (
  0 => 'Notification Settings',
  1 => 'Status',
  2 => 'Notifications',
  3 => 'Automatic notification is <strong>enabled</strong>',
  4 => 'Notifications will be sent out <strong>{$when_to_send_fmt}</strong>',
  5 => 'Notifications will be sent <strong>{$notifications_data.days_to_due}</strong> day(s) before due date and the day it is due',
  6 => 'Notifications will be sent <strong>{$notifications_data.days_to_due}</strong> day(s) before due date',
  7 => 'Notifications will be sent only to <strong>responsible assignee</strong> from the <strong>owner company</strong>',
  8 => 'Notifications will be sent to <strong>all assignees</strong> from the owner company',
  9 => 'Notifications will be sent only to <strong>responsible assignee</strong> regardless of company',
  10 => 'Notifications will be sent to <strong>all assignees</strong> regardless of company',
  11 => 'Automatic notification is <strong>disabled</strong>',
  12 => 'System time (w/o timezone settings) is <strong>{$system_time}',
  13 => 'Settings',
  14 => 'Enable notifications:',
  15 => 'Notify on due date?:',
  16 => 'Notify only responsible assignee?:',
  17 => 'Notify only assignees from owner company?:',
  18 => 'Hour of day to send:',
  19 => 'Notify days in advance:',
  20 => 'days before due date',
  21 => 'Submit',
); ?>